version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: abrigoliterario_db
    restart: always
    # network_mode: host
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: abrigoliterario
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
